#!/bin/sh
set -e

#DEBHELPER#

case $1 in
    remove)
        conflicts="/usr/lib/chromium/chromium-wrapper"
        for i in $conflicts
        do
            dpkg-divert --package rockchip-chromium-x11-utils --rename --remove "$i"
        done
        ;;
esac

exit 0