#!/bin/sh
set -e

case $1 in
    install|upgrade)
        conflicts="/usr/lib/chromium/chromium-wrapper"
        for i in $conflicts
        do
            dpkg-divert --package rockchip-chromium-x11-utils --divert "$i.bak" --rename "$i"
        done
        ;;
esac
    
#DEBHELPER#

exit 0